apiVersion: apps/v1
kind: Deployment
metadata:
  name: seismic
spec:
  selector:
    matchLabels:
      app: seismic
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: seismic
    spec:
      containers:
      - name: seismic
        image: danimalcontainers.azurecr.io/flask:6
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
    name: seismic
spec:
    type: LoadBalancer
    ports:
    - port: 5000
    selector:
        app: seismic
---
apiVersion: v1
kind: Service
metadata:
    name: mongo
spec:
    type: LoadBalancer
    ports:
    - port: 27017
    selector:
        app: mongo